# =====================================================
# Keycloak Theme Metadata — ACME Corp
# =====================================================
parent=keycloak
import=common/keycloak/themes

types=login
styles=css/login.css css/password.css css/webauthn.css
