# =====================================================
# Keycloak Theme Metadata
# =====================================================
parent=keycloak
import=common/keycloak/themes

# Theme type: login, account, admin, email, welcome
types=login

# Display name shown in Keycloak admin console
styles=css/login.css css/password.css css/webauthn.css
